language: node_js
node_js:
  - stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add @gridsome/cli

install:
  - yarn install

script:
  - yarn build

before_deploy:
  - ls -lisah ./dist/

deploy:
  provider: surge
  project: ./dist/
  domain: blugentoleaderboard.surge.sh
  skip_cleanup: true
  on:
    branch: master
