language: node_js
node_js:
  - lts

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add @gridsome/cli

install:
  - yarn install

cache: yarn

script:
  - yarn build

deploy:
  provider: surge
  project: ./dist/
  domain: blugentoleaderboard.surge.sh
  on:
    branch: master
